export default {
  login: jest.fn(),
  register: jest.fn(),
  getCurrentUser: jest.fn(),
  logout: jest.fn(),
  updateProfile: jest.fn(),
  changePassword: jest.fn(),
  requestPasswordReset: jest.fn(),
  resetPassword: jest.fn(),
  isAuthenticated: jest.fn(),
  getAuthHeader: jest.fn(),
  getAccessToken: jest.fn(),
  getRefreshToken: jest.fn(),
  setAuthTokens: jest.fn(),
  clearAuth: jest.fn(),
  isTokenExpired: jest.fn(),
  isRefreshTokenExpired: jest.fn(),
  refreshToken: jest.fn(),
  parseJwt: jest.fn(),
};
